# Configuration Settings for the Rover Rx

/**:
  ros__parameters:
    device: tcp://192.168.110.197:28784

    frame_id: gnss_link

    datum: WGS84

    marker_to_arp:
      delta_e: 0.0
      delta_n: 0.0
      delta_u: 0.0

    ant_type: Unknown
    ant_serial_nr: Unknown

    polling_period:
      pvt: 200
      rest: 200

    reconnect_delay_s: 2

    use_gnss_time: false
    leap_seconds: 18

    publish:
      gpgga: true
      gprmc: false
      gpgsa: false
      gpgsv: false
      pvtcartesian: false  # required to velocity publish
      pvtgeodetic: true  # required to navsatfix publish
      poscovcartesian: false
      poscovgeodetic: true  # required to navsatfix publish
      atteuler: false
      attcoveuler: false
      gpst : false
      navsatfix: true
      gpsfix: false
      pose: false
      velocity: false
      diagnostics: false
